// Example plant data
const plants = [
  {
    name: "Tulsi",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Tulsi_or_Tulasi_Holy_basil.jpg/500px-Tulsi_or_Tulasi_Holy_basil.jpg",
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun to partial shade",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Cough, cold, immunity",
    tips: "Pinch off flower buds to encourage leaf growth.",
    commonMistakes: "Overwatering and poor drainage.",
    funFact: "Known as Holy Basil in English.",
    category: "Herb",
  },
  {
    name: "Aloe Vera",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Aloe_Vera.jpg/500px-Aloe_Vera.jpg",
    season: "All year",
    soil: "Sandy, well-drained",
    sunlight: "Bright, indirect sunlight",
    water: "Low, allow soil to dry between waterings",
    medicinal: "Yes",
    medicalUse: "Skin burns, digestion",
    tips: "Use a pot with drainage holes.",
    commonMistakes: "Overwatering and lack of sunlight.",
    funFact: "Aloe gel is 99% water.",
    category: "Herb",
  },
  {
    name: "Neem",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/500px-Neem_Tree_in_Rajasthan%2C_India.jpg",
    season: "Spring",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Low, drought tolerant",
    medicinal: "Yes",
    medicalUse: "Skin, dental, immunity",
    tips: "Prune regularly to maintain shape.",
    commonMistakes: "Waterlogging roots.",
    funFact: "Neem is called the 'village pharmacy' in India.",
    category: "Herb",
  },
  {
    name: "Money Plant",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/500px-Epipremnum_aureum_31082012.jpg",
    season: "All year",
    soil: "Moist, well-drained",
    sunlight: "Indirect sunlight",
    water: "Moderate, keep soil moist",
    medicinal: "No",
    medicalUse: "Air purification",
    tips: "Can grow in water or soil.",
    commonMistakes: "Direct sunlight burns leaves.",
    funFact: "Believed to bring good luck.",
    category: "Flower",
  },
  {
    name: "Snake Plant",
    image: "https://seed2plant.in/cdn/shop/files/SnakePlantvariegatedIndoorLivePlant-Seed2Plant2.png?v=1720536217&width=750",
    season: "All year",
    soil: "Well-drained, sandy",
    sunlight: "Low to bright indirect light",
    water: "Low, let soil dry completely",
    medicinal: "No",
    medicalUse: "Air purification",
    tips: "Tolerates neglect and low light.",
    commonMistakes: "Overwatering causes root rot.",
    funFact: "Also called Mother-in-law's Tongue.",
    category: "Flower",
  },
  {
    name: "Rose",
    image: "https://seed2plant.in/cdn/shop/files/Orange_Rose_Grafted_Live_Plant-Seed2Plant.png?v=1749467391&width=1780",
    season: "Spring, Summer",
    soil: "Loamy, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Aromatherapy, skin care",
    tips: "Prune in early spring for best blooms.",
    commonMistakes: "Poor air circulation leads to disease.",
    funFact: "There are over 300 species of roses.",
    category: "Flower",
  },
  {
    name: "Jasmine",
    image: "https://seed2plant.in/cdn/shop/files/IMG_1930.heic?v=1692101355&width=750",
    season: "Summer",
    soil: "Well-drained, sandy",
    sunlight: "Full sun to partial shade",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Stress relief, skin care",
    tips: "Provide a trellis for climbing varieties.",
    commonMistakes: "Underwatering in hot weather.",
    funFact: "Jasmine flowers open at night.",
    category: "Flower",
  },
  {
    name: "Mint",
    image: "https://seed2plant.in/cdn/shop/files/SugandhaPepperMintMedicinalLivePlant-Seed2Plant-2.png?v=1713889309&width=750",
    season: "Spring, Summer",
    soil: "Moist, rich",
    sunlight: "Partial shade to full sun",
    water: "High, keep soil consistently moist",
    medicinal: "Yes",
    medicalUse: "Digestion, cold",
    tips: "Grow in pots to prevent spreading.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Mint is a natural insect repellent.",
    category: "Herb",
  },
  {
    name: "Coriander",
    image: "https://seed2plant.in/cdn/shop/products/corianderseeds.jpg?v=1604033330&width=1100",
    season: "Winter, Spring",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Digestion, anti-inflammatory",
    tips: "Sow seeds directly, doesn't transplant well.",
    commonMistakes: "Overcrowding plants.",
    funFact: "Also called cilantro in the Americas.",
    category: "Herb",
  },
  {
    name: "Basil",
    image: "https://seed2plant.in/cdn/shop/files/RamaTulsi_AfricanBasil_MedicinalLivePlant-Seed2Plant-3.png?v=1713883206&width=750",
    season: "Summer",
    soil: "Well-drained, rich",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Antioxidant, anti-inflammatory",
    tips: "Pinch off flower buds to prolong harvest.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Basil is sacred in many cultures.",
    category: "Herb",
  },
  {
    name: "Marigold",
    image: "https://seed2plant.in/cdn/shop/files/Tageteserecta-seed2plant.jpg?v=1699434271&width=750",
    season: "Summer, Autumn",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, drought tolerant",
    medicinal: "Yes",
    medicalUse: "Skin healing, anti-inflammatory",
    tips: "Deadhead spent flowers for more blooms.",
    commonMistakes: "Overwatering.",
    funFact: "Marigolds are used in festivals in India.",
    category: "Flower",
  },
  {
    name: "Peepal",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Ficus_religiosa_Bo.jpg/500px-Ficus_religiosa_Bo.jpg",
    season: "All year",
    soil: "All types",
    sunlight: "Full sun",
    water: "Low, drought tolerant",
    medicinal: "Yes",
    medicalUse: "Asthma, diabetes",
    tips: "Needs space to grow large.",
    commonMistakes: "Planting too close to buildings.",
    funFact: "Buddha attained enlightenment under a Peepal tree.",
    category: "Flower",
  },
  {
    name: "Bamboo",
    image: "https://seed2plant.in/cdn/shop/files/GoldenBamboo_Phyllostachysaurea_LivePlant-Seed2Plant-2.png?v=1750486302&width=750",
    season: "All year",
    soil: "Well-drained, loamy",
    sunlight: "Full sun to partial shade",
    water: "High, keep soil moist",
    medicinal: "No",
    medicalUse: "Construction, crafts",
    tips: "Control spread with barriers.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Bamboo is the fastest growing plant.",
    category: "Flower",
  },
  {
    name: "Curry Leaf",
    image: "https://seed2plant.in/cdn/shop/files/licensed-image_c4a7ff7f-b6c1-4284-8400-4360f2d269a7.jpg?v=1683812677&width=1100",
    season: "All year",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Digestion, diabetes",
    tips: "Prune regularly for bushier growth.",
    commonMistakes: "Overwatering.",
    funFact: "Essential in South Indian cuisine.",
    category: "Herb",
  },
  {
    name: "Lemongrass",
    image: "http://5.imimg.com/data5/SELLER/Default/2023/8/335024320/VK/OK/CN/126345476/lemongrass-1000x1000.jpg",
    season: "Summer",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Fever, digestion",
    tips: "Harvest stalks from the outside.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Used in teas and aromatherapy.",
    category: "Herb",
  },
  {
    name: "Hibiscus",
    image: "https://seed2plant.in/cdn/shop/files/Hibiscusyellow-seed2plant.jpg?v=1702239704&width=750",
    season: "Summer, Autumn",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Hair care, blood pressure",
    tips: "Prune after flowering for more blooms.",
    commonMistakes: "Underwatering.",
    funFact: "Hibiscus tea is rich in vitamin C.",
    category: "Flower",
  },
  {
    name: "Mango",
    image: "https://seed2plant.in/cdn/shop/files/natural-and-green-banganapalli-mango-with-6-days-shelf-life-and-rich-in-vitamin-c-414.jpg?v=1683639738&width=750", 
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, deep watering",
    medicinal: "Yes",
    medicalUse: "Digestion, immunity",
    tips: "Protect young trees from frost.",
    commonMistakes: "Overwatering young trees.",
    funFact: "Mango is the national fruit of India.",
    category: "Fruit",
  },
  {
    name: "Guava",
    image: "https://seed2plant.in/cdn/shop/products/Layer_11_600x_1.webp?v=1704692934&width=1100", // Guava tree
    season: "Winter, Summer",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Immunity, digestion",
    tips: "Thin fruits for better size and quality.",
    commonMistakes: "Overcrowding branches.",
    funFact: "Guava leaves are used in herbal teas.",
    category: "Fruit",
  },
  {
    name: "Banana",
    image: "https://seed2plant.in/cdn/shop/files/Ethapazham-or-Nendra-Pazham-1024x754.jpg?v=1699097100&width=1100", // Banana plant
    season: "All year",
    soil: "Fertile, well-drained",
    sunlight: "Full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Digestion, energy",
    tips: "Mulch heavily for moisture retention.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Bananas are technically berries.",
    category: "Fruit",
  },
  {
    name: "Papaya",
    image: "https://seed2plant.in/cdn/shop/files/VietnamYellowPapayaFruitLivePlant-Seed2Plant-3.png?v=1741852541&width=1100", // Papaya plant
    season: "All year",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Digestion, skin care",
    tips: "Protect from strong winds.",
    commonMistakes: "Overwatering.",
    funFact: "Papaya contains the enzyme papain.",
    category: "Fruit",
  },
  {
    name: "Tomato",
    image: "https://seed2plant.in/cdn/shop/products/tomatoseeds.jpg?v=1604033216&width=1100", // Tomato plant
    season: "Summer",
    soil: "Loamy, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamins, antioxidant",
    tips: "Stake plants for support.",
    commonMistakes: "Overwatering and poor air circulation.",
    funFact: "Tomatoes are technically berries.",
    category: "Vegetable",
  },
  {
    name: "Carrot",
    image:"https://harvesttotable.com/wp-content/uploads/2009/02/bigstock-176253796-scaled.jpg",
    season: "Winter, Spring",
    soil: "Loose, sandy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Good for eyesight, rich in beta-carotene",
    tips: "Thin seedlings for bigger roots.",
    commonMistakes: "Heavy, rocky soil causes misshapen roots.",
    funFact: "Carrots were originally purple or yellow.",
    category: "Vegetable",
  },
  {
    name: "Spinach",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg/500px-Spinacia_oleracea_Spinazie_bloeiend.jpg",
    season: "Winter, Spring",
    soil: "Moist, rich",
    sunlight: "Partial shade to full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in iron and vitamins",
    tips: "Harvest leaves before flowering.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Spinach was made famous by Popeye.",
    category: "Vegetable",
  },
  {
    name: "Cabbage",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Chou_1.jpg/500px-Chou_1.jpg",
    season: "Winter, Spring",
    soil: "Moist, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin C, anti-inflammatory",
    tips: "Space plants well for large heads.",
    commonMistakes: "Overcrowding and poor drainage.",
    funFact: "Cabbage has been grown for over 4,000 years.",
    category: "Vegetable",
  },
  {
    name: "Potato",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTgV1JYf_AGA8MPr2853PAqvwyLYIbg5yqeADeSQV0XL_g7MvYPyeAr2WUy9HtjiQEGP11KEJ-Yh3nPidBkB8azR71F-4wNLxDtlMwRa6H_",
    season: "Winter, Spring",
    soil: "Loose, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "No",
    medicalUse: "High in carbs, energy source",
    tips: "Hill soil around stems as they grow.",
    commonMistakes: "Planting in wet, heavy soil.",
    funFact: "Potatoes were the first vegetable grown in space.",
    category: "Vegetable",
  },
  {
    name: "Onion",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTCJS2dxMte07AwOc8dDTjT_hJ2VMSMPxVBcgDbGZZQpDteQihxYIClEpolEqY6JD6xSFifBna9JJCJoEjbPeWicp4d4RAKrJReJrXs78B7pA",
    season: "Winter, Spring",
    soil: "Loose, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Antibacterial, heart health",
    tips: "Harvest when tops fall over.",
    commonMistakes: "Overwatering causes rot.",
    funFact: "Onions are one of the oldest cultivated crops.",
    category: "Vegetable",
  },
  {
    name: "Brinjal",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/440px-Solanum_melongena_24_08_2012_%281%29.JPG",
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in fiber, antioxidants",
    tips: "Stake plants to support heavy fruit.",
    commonMistakes: "Overwatering and poor drainage.",
    funFact: "Brinjal is also called eggplant or aubergine.",
    category: "Vegetable",
  },
  {
    name: "Pumpkin",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqTy8t1clBNDbyqAV_eyw1AP-yz3pjVifpz1R_ipVx0gKQN6cuYyCEuSM&s",
    season: "Summer, Autumn",
    soil: "Rich, well-drained",
    sunlight: "Full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin A, good for eyes",
    tips: "Provide space for vines to spread.",
    commonMistakes: "Planting too close together.",
    funFact: "Pumpkins are 90% water.",
    category: "Vegetable",
  },
  {
    name: "Radish",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9MmOLn5MrLeWJFC0-ubhOgnEcZCdH8hCw_bnKGEY7xAFFOsEGbuH__ffzLSmXynHXGhRAqrQ0eYq09nNR49eCnDnZRmxreW9PQa-DOxkv",
    season: "Winter, Spring",
    soil: "Loose, sandy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Good for digestion, detox",
    tips: "Harvest when roots are young and tender.",
    commonMistakes: "Letting roots get too large and woody.",
    funFact: "Radishes can be harvested in as little as 3 weeks.",
    category: "Vegetable",
  },
  {
    name: "Cauliflower",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqv5mepz-BP-ywvSP9VpP8ccuaGWsR5DA8sg&s",
    season: "Winter, Spring",
    soil: "Rich, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin C, fiber",
    tips: "Blanch heads for white curds.",
    commonMistakes: "Exposure to sun causes yellowing.",
    funFact: "Cauliflower comes in purple, orange, and green varieties.",
    category: "Vegetable",
  },
  {
    name: "Chili Pepper",
    image:"https://apps.rhs.org.uk/plantselectorimages/detail/GWIS174.jpg",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Boosts metabolism, vitamin C",
    tips: "Harvest when fully colored.",
    commonMistakes: "Overwatering and poor drainage.",
    funFact: "Chili peppers originated in the Americas.",
    category: "Vegetable",
  },
  {
    name: "Cucumber",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/500px-ARS_cucumber.jpg",
    soil: "Rich, well-drained",
    sunlight: "Full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Hydration, skin care",
    tips: "Provide a trellis for climbing.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Cucumbers are 95% water.",
    category: "Vegetable",
  },
  {
    name: "Pea",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Doperwt_rijserwt_peulen_Pisum_sativum.jpg/500px-Doperwt_rijserwt_peulen_Pisum_sativum.jpg",
    season: "Winter, Spring",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in protein, fiber",
    tips: "Harvest pods when young and tender.",
    commonMistakes: "Letting pods mature too long.",
    funFact: "Peas are one of the oldest cultivated crops.",
    category: "Vegetable",
  },
  {
    name: "Okra",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Okra%28Abelmoschus_esculentus%29.JPG/500px-Okra%28Abelmoschus_esculentus%29.JPG",
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Good for digestion, rich in fiber",
    tips: "Harvest pods when small and tender.",
    commonMistakes: "Letting pods get too large and tough.",
    funFact: "Okra is also called lady's finger.",
    category: "Vegetable",
  },
  {
    name: "Apple",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Apfelbaum_Winterrambour_Hochstamm.jpg/1280px-Apfelbaum_Winterrambour_Hochstamm.jpg",
    season: "Autumn",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, deep watering",
    medicinal: "Yes",
    medicalUse: "Rich in fiber, heart health",
    tips: "Thin fruits for better size.",
    commonMistakes: "Overcrowding branches.",
    funFact: "There are over 7,500 varieties of apples.",
    category: "Fruit",
  },
  {
    name: "Grapes",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Abhar-iran.JPG/330px-Abhar-iran.JPG",
    season: "Summer, Autumn",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, deep watering",
    medicinal: "Yes",
    medicalUse: "Rich in antioxidants, heart health",
    tips: "Prune vines annually for best yield.",
    commonMistakes: "Overwatering and poor air circulation.",
    funFact: "Grapes are one of the oldest cultivated fruits.",
    category: "Fruit",
  },
  {
    name: "Pomegranate",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRGhRdE_pAretJjXYukyUcoSeb5cIiPJmp6n-dd_KJoCUKejjMiMfZ0KVCL2-ejHgICTCBHVGjmeMt76Wp1MyfxY__xpYOXxX7jHlmxjDKo",
    season: "Autumn",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Rich in antioxidants, immunity",
    tips: "Prune for shape and airflow.",
    commonMistakes: "Overwatering young plants.",
    funFact: "Pomegranates have over 600 seeds each.",
    category: "Fruit",
  },
  {
    name: "Strawberry",
    image: "https://strawberryplants.org/wp-content/uploads/Growing-Strawberries-in-Containers-featured.jpg", // Strawberry plant
    season: "Spring, Summer",
    soil: "Rich, well-drained",
    sunlight: "Full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin C, skin health",
    tips: "Mulch to keep berries clean.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Strawberries are the only fruit with seeds on the outside.",
    category: "Fruit",
  },
  {
    name: "Pineapple",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/500px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg",
    season: "All year",
    soil: "Sandy, well-drained",
    sunlight: "Full sun",
    water: "Moderate, let soil dry slightly",
    medicinal: "Yes",
    medicalUse: "Aids digestion, rich in vitamin C",
    tips: "Grow from the crown of a mature fruit.",
    commonMistakes: "Overwatering and poor drainage.",
    funFact: "Pineapples take up to 2 years to mature.",
    category: "Fruit",
  },
  {
    name: "Lettuce",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Iceberg_lettuce_in_SB.jpg/500px-Iceberg_lettuce_in_SB.jpg",
    season: "Winter, Spring",
    soil: "Moist, rich",
    sunlight: "Partial shade to full sun",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamins, hydration",
    tips: "Harvest leaves from the outside.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Lettuce was first cultivated by the ancient Egyptians.",
    category: "Vegetable",
  },
  {
    name: "Daisy",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUvqXwpLC3wCnQ9bKSlDGSJXddXlSJ6vz5fGdoxThBY5I4ApUyoTlRm_dyn39YoG53SwV3fjy8wfzeCwGxXlPjkfoBAouFq5ziT9c_8zam",
    season: "Spring, Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun to partial shade",
    water: "Moderate, keep soil moist",
    medicinal: "No",
    medicalUse: "Ornamental",
    tips: "Deadhead spent flowers for more blooms.",
    commonMistakes: "Overwatering.",
    funFact: "Daisies symbolize innocence and purity.",
    category: "Flower",
  },
  {
    name: "Sunflower",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQRWZDgtAq4HgP-VSsGUaYu64DiXJPdnnwHD_9_srS92wgEn3oV8b9lTYCpBrRErW_w0CMglpC5B2qCPVy4O2MJtkcpKAENv6ng-r3Jn1VOGA",
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, deep watering",
    medicinal: "No",
    medicalUse: "Seeds are edible, oil source",
    tips: "Plant in a sunny, sheltered spot.",
    commonMistakes: "Planting in shade.",
    funFact: "Sunflowers can grow over 3 meters tall.",
    category: "Flower",
  },
  {
    name: "Lavender",
    image: "https://m.media-amazon.com/images/I/71toNci7wWL.jpg",
    season: "All year",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Low, drought tolerant",
    medicinal: "Yes",
    medicalUse: "Memory, digestion",
    tips: "Trim regularly to keep bushy.",
    commonMistakes: "Overwatering and poor drainage.",
    funFact: "Rosemary is a symbol of remembrance.",
    category: "Herb",
  },
  {
    name: "Tulip",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgCTPMEZpDp9FPzLu7d9JGySVF7CXSOD-CAfZi3V9hyH5fthy1ljHX7LprWylO2ougoVlNAJuDVtTRfaSikvDkHc-hRVScsZ9yXg6Q1X-0",
    season: "Spring",
    soil: "Well-drained, sandy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "No",
    medicalUse: "Ornamental",
    tips: "Plant bulbs in autumn.",
    commonMistakes: "Planting bulbs too shallow.",
    funFact: "Tulips were once more valuable than gold.",
    category: "Flower",
  },
  {
    name: "Chrysanthemum",
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSJqpL6nZUQiJar7UGP6RMl1pHKt9a0gZeY_8TmJ-fl-jVlvqW4-7K5K2dabpVL6n3Qsl8AHiUvlgO-plLVy4rzrHwtH1Jeyp1a_cn_rzBB",
    season: "Spring, Summer",
    soil: "Moist, rich",
    sunlight: "Full sun to partial shade",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin K, digestion",
    tips: "Harvest outer leaves first.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Parsley is one of the most popular herbs in the world.",
    category: "Herb",
  },
  {
    name: "Zinnia",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQNAp5BGvmoMMq5PYgNpQVebIunb1OxKFCAi8Bra1mH-Fei3XhA1aRdEFccbeosA5RaF-4UMRO1xpiQ0_gdC4tWSSOjzKo7TzrlMz79Q_V_FQ",
    season: "Summer",
    soil: "Well-drained, loamy",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "No",
    medicalUse: "Ornamental",
    tips: "Deadhead for continuous blooms.",
    commonMistakes: "Overwatering.",
    funFact: "Zinnias are native to Mexico.",
    category: "Flower",
  },
  {
    name: "Celery",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeFmroe9ScN3T3T4keBAWJV5eKqRSABaai4VGTjzbDvMcE1yyXgfORJtg6KaPMIwC57grgE0QlUUD9lmZGwA4TcY6JVtcz6Ni5vFPHzj3bkQ",
    season: "Winter, Spring",
    soil: "Moist, rich",
    sunlight: "Full sun to partial shade",
    water: "High, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamins, hydration",
    tips: "Keep soil consistently moist.",
    commonMistakes: "Letting soil dry out.",
    funFact: "Celery was used as a flavoring in ancient Greece.",
    category: "Vegetable",
  },
  {
    name: "Broccoli",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSZkiaA93drHB7zURGBcyADQv2tEYESpjqEK8NKXSTL2FVvSxaDd9ZlR2Ff61o38DuQuU6IbwG2Px59-U2PuzrSlkZwDY1F-OCPJK1BDU2Q",
    season: "Winter, Spring",
    soil: "Rich, well-drained",
    sunlight: "Full sun",
    water: "Moderate, keep soil moist",
    medicinal: "Yes",
    medicalUse: "Rich in vitamin C, fiber",
    tips: "Harvest heads before flowers open.",
    commonMistakes: "Letting heads flower.",
    funFact: "Broccoli was developed from wild cabbage.",
    category: "Vegetable",
  },
];

let currentCategory = null;

function displayPlants(list, category = null) {
  const plantList = document.getElementById('plantList');
  plantList.innerHTML = '';
  let heading = '';
  if (category) {
    heading = `<h3 style="text-align:center;">${category}s</h3>`;
  }
  if (list.length === 0) {
    plantList.innerHTML = heading + '<p style="text-align:center; color: #888;">No plant found.</p>';
    return;
  }
  plantList.innerHTML = heading;
  list.forEach(plant => {
    plantList.innerHTML += `
      <div class="plant-card">
        <img src="${plant.image}" alt="${plant.name}">
        <h4>${plant.name}</h4>
        <p><b>Season:</b> ${plant.season}</p>
        <p><b>Soil:</b> ${plant.soil}</p>
        <p><b>Sunlight:</b> ${plant.sunlight}</p>
        <p><b>Water:</b> ${plant.water}</p>
        <p><b>Medicinal:</b> ${plant.medicinal}</p>
        <p><b>Use:</b> ${plant.medicalUse}</p>
        <p><b>Tips:</b> ${plant.tips}</p>
        <p><b>Common Mistakes:</b> ${plant.commonMistakes}</p>
        <p><i>${plant.funFact}</i></p>
      </div>
    `;
  });
}

document.getElementById('searchBar').addEventListener('input', function(e) {
  const query = e.target.value.toLowerCase();
  const filtered = plants.filter(plant =>
    plant.name.toLowerCase().includes(query) ||
    plant.season.toLowerCase().includes(query) ||
    plant.soil.toLowerCase().includes(query) ||
    plant.medicalUse.toLowerCase().includes(query)
  );
  displayPlants(filtered, currentCategory);
});

// Category click handlers
window.addEventListener('DOMContentLoaded', function() {
  const categoryCards = document.querySelectorAll('.category-card');
  categoryCards.forEach(card => {
    card.addEventListener('click', function(e) {
      e.preventDefault();
      const category = card.textContent.trim().replace(/s$/, ''); // Remove plural s
      currentCategory = category;
      const filtered = plants.filter(plant => plant.category === category);
      displayPlants(filtered, category);
    });
  });
});

// Initial display
displayPlants(plants);